import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Ticker from "@/components/Ticker";
import CoinList from "@/components/CoinList";
import Banner from "@/components/Banner";
import TopCoins from "@/components/TopCoins";

export const metadata = {
  title: `CSI-Play `,
  description: "Generated by CSI-Play",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between min-h-screen pt-16 bg-gray-300/70 ">
        <Header />
        <main className="flex-1 mt-2">
          <Ticker />
          <section className="section">
            <div className="grid grid-cols-1 xl:grid-cols-12 w-full xl:gap-2">
              {/* Left Side Section Level 1*/}
              <div className="xl:col-span-10">{children}</div>
              {/* Right Side Section */}
              <div className="xl:col-span-2">
                {/* Sign In and Best Coin List */}
                <div className="hidden xl:block">
                  <CoinList />
                </div>
                <Banner />
                <TopCoins />
              </div>
            </div>
          </section>
        </main>
        <Footer />
      </body>
    </html>
  );
}
