import "../styles/globals.css";
import Nav from "@/components/Nav";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
        <Script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></Script>
      </body>
    </html>
  );
}
