import "../styles/globals.css";
import Header from "@/components/Navigation/Header";
import Footer from "@/components/Footer/Footer";
import Ticker from "@/components/Ticker";

export const metadata = {
  title: `CSI-Play `,
  description: "Generated by CSI-Play",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-300 text-sm">{children}</body>
    </html>
  );
}
