import "../styles/globals.css";

export const metadata = {
  title: `CSI-Play `,
  description: "Generated by CSI-Play",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-200/50 text-sm mx-auto max-w-[1920px]">
        {children}
      </body>
    </html>
  );
}
